manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: lander03xd
      url-base: https://github.com/lander03xd
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    # Adding my own custom behavior
    - name: zmk-behavior-morse
      remote: lander03xd
      revision: main
      path: modules/zmk-module-lander03xd
  self:
    path: config
